k8-proxy/p-k8-jmeter-test-engine

upwork-devs/harut.grigoryan/controlling-jmeter-pod/docker-jmeter-c-icap/Test/launch.sh, upwork-devs/harut.grigoryan/controlling-jmeter-pod/docker-jmeter-c-icap/processor.py
The version uploads jmeter report to minio.
=> Jmeter report

.github/workflows/deploy_common_res.yaml
=> comment ELK from deployment automation

.github/workflows/deploy_common_res.yaml, .github/workflows/docker_ci.yaml, kubernetes/common_resources/README.md, kubernetes/common_resources/influxdb/influxdb.yaml, kubernetes/common_resources/influxdb/init-influxdb.iql
* add influxdb initialization script to create databases automatically
* move influxdb files to separate dir
=> add initialization script for influxdb

src/controller/recommendations.md
=> Closes #77

terraform/eks/README.md, terraform/eks/eks-cluster.tf
* add taints to node-groups
* update README.md
=> Eks terraform

Dockerfiles/README.md, Dockerfiles/jmeter-base, Dockerfiles/jmeter-testdata
* update Dockerfiles
* update README.md
=> Docker Images

src/s3-to-minio/files.csv, src/s3-to-minio/s3-to-minio.py
Improved version of the script that retries Minio uploads in case of failures
=> Issue 68 1

eks_app_dep.py
Run Python Script from following commands to deploy N number of Pods with N number of user
python3 eks_dep.py -u 2 (Number of Users)
=> Task:-104 :- Implement the mechanism to dynamically create k8 pods based on the number of users.pods deployment by python script.

.github/workflows/deploy_common_res.yaml
- update helm chart default repo
=> update helm chart repo

.gitignore, helm-charts/common-resources/aws.yaml, helm-charts/common-resources/templates/minio-storage.yaml, helm-charts/common-resources/templates/minio.yaml, terraform/eks/.gitignore, terraform/eks/cluster-autoscaler-autodiscover.yaml, terraform/eks/efs.tf, terraform/eks/eks-cluster.tf, terraform/eks/local-provisioner.tf, terraform/eks/terraform.tfvars, terraform/eks/variables.tf, terraform/eks/vpc.tf
- add generic name
- add autoscaling tag
- update local provisioning
- update storage driver
- update efs_id with terraform
- enable s3 remote state
- enable efs persistent storage
=> EKS Persistent Storage

jmeter-icap/scripts/README.md
- Removed some of the leftover AWS related documentation
- Updated broken links
- Added entries for new parameters where relevant
=> Ali modifying instructions: Updated instructions to remove AWS related material and add new parameters

deployment/helm-charts/common-resources/local.yaml, deployment/helm-charts/common-resources/requirements.yaml, deployment/helm-charts/common-resources/templates/grafana-storage.yaml, deployment/helm-charts/common-resources/templates/influxdb-storage.yaml, deployment/helm-charts/common-resources/templates/minio-storage.yaml
- Added multiple services into current helm chart
- promtail
- prometheus
- loki
- Enable persistent storage for prometheus
=> microk8s: update helm chart

jmeter-icap/scripts/create_dashboard.py
Added method to get number of pods from create_stack and use them in math calculation for number of users and errors panel of Grafana template
=> Updated create_dashboard.py

.gitignore, jmeter-icap/scripts/create_stack_dash.py, jmeter-icap/scripts/requirements.txt, jmeter-icap/ui/master-script-form/src/app/common/Validators/ConfigFormValidators.ts, jmeter-icap/ui/master-script-form/src/app/config-form/config-form.component.html, jmeter-icap/ui/master-script-form/src/app/config-form/config-form.component.ts
- UI: Removed unused field in form and added improved validation in UI form, no whitespaces allowed
- Updated requirements file to include required packages
- removed hardcoding localhost for Grafana installation
- added logic to create error if no Grafana key is provided via config.env
=> Ali integrating UI: Improved UI validation, removed some bugs

jmeter-icap/scripts/create_stack_dash.py
- Delete stack timer in master script (which was holding up execution preventing dashboard from being sent to UI front end) now runs on a separate thread.
=> Update create_stack_dash.py to fix bug where UI was not receiving Grafana Dashboard link

jmeter-icap/scripts/create_stack_dash.py
Implemented threading for create_stack as well as delete_stack so that these processes do not block dashboard URL from being sent to UI front end
=> Update create_stack_dash.py: Fix for dashboard creation and posting on UI being slightly delayed

instructions/How to deploy Angular UI and Flask Server as Service.md
Added instructions from AWS project to this one, the same steps are required in both applications so no changes have been made.
=> Added file How to deploy Angular UI and Flask Server as Service.md

instructions/How to deploy OVA.md
=> Update How to deploy OVA.md

jmeter-icap/scripts/create_stack.py, jmeter-icap/scripts/create_stack_dash.py
Create_stack_dash: Incorrect use of threading when calling create stack has been fixed. TLS true/false value method of passing to create_stack has been improved to work with original create_stack script
create_stack: TLS value should pass correctly between scripts
=> Ali fixing bugs: create_stack_dash threading issue, create_stack and create_stack_dash TLS field issue

jmeter-icap/scripts/create_stack_dash.py, jmeter-icap/scripts/flask_server.py
- Fixed incorrect config fields in method "__ui_set_files_for_load_type"
- Fixed mistake in flask_server where returned URL was assigned twice
=> Fixed bug related to variable names incorrect values to occur in Config object

jmeter-icap/scripts/create_stack_dash.py
Added parameter to create_stack_dash such that it passes it to create_stack script
=> Updated create_stack_dash.py to pass proxy_static_ip parameter

UI/master-script-form/src/app/config-form/config-form.component.ts, jmeter-icap/scripts/create_stack_dash.py
- Create_stack_dash: Timed delete operations now target correct stacks, also fixed messaging related to when stack will be deleted
- Create_stack process will now block return message to form in order to prevent users from spamming test requests too fast
- UI: Fixed small bug where form did not properly lock after submitting test
=> Fixing bugs related to stack deletion

jmeter-icap/scripts/create_stack_dash.py
Fixed issue where config was not being correctly initialized
=> Ali- fixing bug

instructions/How to use k8 test engine using create_stack_dash.py.md
- Added entries for Grafana username/password, three Sharepoint params in table of parameters and config.env example
=> Ali Added instructions for new parameters used in create_stack_dash

instructions/How to use k8 test engine using create_stack_dash.py.md
Modified create_stack_dash instructions to include new Sharepoint parameters
=> Modified instructions file: k8 test engine using create_stack_dash.py.md

jmeter-icap/scripts/ICAP-Direct-File-Processing/k8-test-engine-dashboard.json, jmeter-icap/scripts/create_stack_dash.py, jmeter-icap/scripts/metrics.py
Reverts k8-proxy/p-k8-jmeter-test-engine#354
=> Revert "Direct load dashboard error rate panel "
